Website-viewer
paranext/platform-bible-sample-extensions pull request #14
Opened 2024-11-22 10:02 UTC by Sebastian-ubs

new pr as follow up of #13

This is the ground work for a generic, config driven online resource viewer extensions.

This includes
- Showing how to add commands that spawn web pages inside of Platform
- example web pages
- reloading pages on scripture reference and scroll group changes, so that web pages stay up to date with the current scripture reference
- retaining the web page on layout changes and restart of platform

👉 [Demo](https://drive.google.com/file/d/1qvToylTsfNxcSU8cQPzJclwupIx4JbRN/view?usp=sharing)

2024-11-22 10:07 UTC, Sebastian-ubs commented
interestingly git shows commits in order of their creation date, but the order I applied them on this branch is actually
1. creating the extension with `npm run create-extension -- website-viewer`
2. merging the relevant previously done work from `web-viewer` branch into this
3. small fixes on top

![image](https://github.com/user-attachments/assets/babff070-1d62-4d5d-bce6-0119f4f9411b)

2024-11-25 14:26 UTC, Sebastian-ubs commented
as mentioned in #13

Interesting files to review are
- main.ts
- webViewerOptions.ts

Maybe
- types/online-resource-viewer.d.ts
- contributions/menus.json
- contributions/localizedStrings.json

2024-11-25 17:29 UTC, tjcouch-sil reviewed
Thanks for doing this! Thanks also for the rework to use `create-extension`. That's really helpful, and I appreciate your time. Just wanted to publish what I have reviewed so far since I need to shift gears. Will come back to this at some point

> Reviewed 35 of 41 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-:-OCZM_SD2m848-1DLvfn:b-47yuqy)* status: 37 of 41 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 11:50 UTC, Sebastian-ubs commented
How to add a new resource: example https://github.com/paranext/platform-bible-sample-extensions/pull/14/commits/58aa0398dd7951b7000677d7acea1bc4a56dd7ca

2024-11-26 18:07 UTC, tjcouch-sil requested changes
Awesome!! Thanks for the great work :) I have a few blocking comments, a non-blocking comment or two (you can resolve if you don't want to take action), and many info comments (no action needed unless you want to do something). Looking forward to having this in!

> Reviewed 2 of 41 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-:-OCddnbYA2VL8m6jxDz4:bqboxyz)* status: all files reviewed, 8 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`src/website-viewer/src/types/website-viewer.d.ts` line 6 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCd_jdJ6rBlaCgbaNd_:-OCd_jdJ6rBlaCgbaNda:b-mgd9sm) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/types/website-viewer.d.ts#L6)):*
> ```XML
>   export interface CommandHandlers {
>     /**
>      * Opens a new Website Viewer web view with a code sandbox mockup and returns the web view id
> ```

These commands don't open a new web view if there is already an existing one at that url, right? Probably worth mentioning here
___
*[`src/website-viewer/src/types/website-viewer.d.ts` line 77 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCd_T5vCoR9Z6ejhFwq:-OCd_T5vCoR9Z6ejhFwr:b-aimqwr) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/types/website-viewer.d.ts#L77)):*
> ```XML
>      * @returns
>      */
>     'dummy.dummy': () => Promise<string | undefined>;
> ```

If you are able to get rid of the `SATISFY_TS_KEY` thing like I suggested, you should hopefully be able to remove this as well
___
*[`src/website-viewer/src/main.ts` line 136 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_jdtj7i0XfXmxmMun:-OC_jdtj7i0XfXmxmMuo:bhio6ft) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L136)):*
> ```XML
>   scrollGroupRef: ScrollGroupScrRef | undefined,
> ): Promise<ScriptureReference> {
>   if (scrollGroupRef === undefined) return papi.scrollGroups.getScrRef();
> ```

FYI passing `undefined` is the same as passing nothing for a parameter, so you could combine this line and the next into one :)

(please note there are many comments that are just informational comments. Don't feel any pressure to take action on them unless you want to)
___
*[`src/website-viewer/src/main.ts` line 191 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_khY5EXpbcoS76esm:-OC_khY5EXpbcoS76esn:b-y6sh40) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L191)):*
> ```XML
>   if (typeof oldRef === 'number' && typeof newRef === 'number') return oldRef !== newRef;
>   // both no scroll group, need to detect object difference
>   if (isScrRef(oldRef) && isScrRef(newRef)) return !deepEqual(oldRef, newRef);
> ```

FYI we have a `platform-scripture-utils` function we usually use for comparing two `scrRefs` called `compareScrRefs`. If it returns other than 0, they're not equal :)
___
*[`src/website-viewer/src/main.ts` line 199 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_kyyq-sYTbR4ntZAf:-OC_kyyq-sYTbR4ntZAg:bew0n1) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L199)):*
> ```XML
> async function getUserLanguageCode(): Promise<string> {
>   // TODO: implement
>   return 'NOT_YET_IMPLEMENTED';
> ```

FYI if you're looking for the interface languages, you can run `papi.settings.get('platform.interfaceLanguage')`. Note it is a string array, not just a string
___
*[`src/website-viewer/src/main.ts` line 212 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdZ4Y--B0REA91-HJm:-OCdZ4Y--B0REA91-HJn:b-hgtmwf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L212)):*
> ```XML
>   // When the scripture reference changes, re-render the last webview of type "websiteViewerWebViewType"
>   // This is not fired in case of "no scroll group", this is handled inside the scroll group change code
>   papi.scrollGroups.onDidUpdateScrRef((scrollGroupUpdateInfo: ScrollGroupUpdateInfo) => {
> ```

This and all these following events return `unsubscriber`s that need to be run to deactivate your extension. Please add them to `context.registrations` :)
___
*[`src/website-viewer/src/main.ts` line 240 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_rSB29B6wzidFTlCx:-OC_rSB29B6wzidFTlCy:b-4k2062) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L240)):*
> ```XML
>     if (!commandByWebViewId.has(webViewId)) return;
> 
>     const command = commandByWebViewId.get(webViewId) || SATISFY_TS_KEY;
> ```

I think you shouldn't need to use something like `SATISFY_TS_KEY`. Here, you can instead just return if `command` is undefined after this line.
___
*[`src/website-viewer/src/main.ts` line 283 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_pNln7j92QgWtI4or:-OC_pNln7j92QgWtI4os:b-as5393) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L283)):*
> ```XML
>   context.registrations.add(await websiteViewerWebViewProviderPromise);
>   Promise.all(commandPromises)
>     .then((arr) => context.registrations.add(...arr))
> ```

Though it is nice and convenient to use the old promise chain syntax sometimes, the [code style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide) says to avoid using it where possible unless there is a compelling reason. Please change this to use `await` and `try/catch` or add a compelling reason in a code comment
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 14 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdbeUD9p3g1DHju3fA:-OCdbeUD9p3g1DHju3fB:bvs8xhu) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L14)):*
> ```XML
> // satisfy typescript, although we do not expect these to appear
> export const SATISFY_TS_KEY: keyof CommandHandlers = 'dummy.dummy';
> export const SATISFY_TS_OPTIONS: WebsiteViewerOptions = {
> ```

This name is a bit confusing. This object is generally used as a sort of "default" object for `WebsiteViewerOptions` when there isn't another one, right? Maybe consider renaming `DEFAULT_WEBSITE_VIEWER_OPTIONS`?
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 24 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdaFQpAVa0LI5yk-Sj:-OCdaFQpAVa0LI5yk-Sk:b-4shecz) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L24)):*
> ```XML
> 
> export enum RefChange {
>   DO_NOT_WATCH,
> ```

We have traditionally made enumeration members `PascalCase` :) but I don't think we have explicit style rules about it, so do what you want with this information
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 30 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdc3R7DIthnZd-pLBe:-OCdc3R83Gm_TQeJHXT1:bs1doa3) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/ [...]

2024-11-27 14:29 UTC, Sebastian-ubs reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14)* status: 36 of 42 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/website-viewer/src/main.ts` line 136 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_jdtj7i0XfXmxmMun:-OChrq3qBKcm_qb-er-M:b-lhs69o) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L136)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FYI passing `undefined` is the same as passing nothing for a parameter, so you could combine this line and the next into one :)

(please note there are many comments that are just informational comments. Don't feel any pressure to take action on them unless you want to)
</blockquote></details>

done, thanks
___
*[`src/website-viewer/src/main.ts` line 191 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_khY5EXpbcoS76esm:-OChsvKm08QcjeOQIgFy:b-k26zla) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L191)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FYI we have a `platform-scripture-utils` function we usually use for comparing two `scrRefs` called `compareScrRefs`. If it returns other than 0, they're not equal :)
</blockquote></details>

done  - although I am wondering about the real difference. comparing the two objects seems to work similarly good.
___
*[`src/website-viewer/src/main.ts` line 199 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_kyyq-sYTbR4ntZAf:-OChtHhuD4I0BztPzGR6:b3axgw) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L199)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FYI if you're looking for the interface languages, you can run `papi.settings.get('platform.interfaceLanguage')`. Note it is a string array, not just a string
</blockquote></details>

❤️
___
*[`src/website-viewer/src/main.ts` line 212 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdZ4Y--B0REA91-HJm:-OChv6t59iSHMQMN6wV0:bb7f2mf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L212)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This and all these following events return `unsubscriber`s that need to be run to deactivate your extension. Please add them to `context.registrations` :)
</blockquote></details>

done
___
*[`src/website-viewer/src/main.ts` line 240 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_rSB29B6wzidFTlCx:-OChvBkl7EkY1Slvw6PY:bb7f2mf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L240)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think you shouldn't need to use something like `SATISFY_TS_KEY`. Here, you can instead just return if `command` is undefined after this line.
</blockquote></details>

done
___
*[`src/website-viewer/src/main.ts` line 283 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_pNln7j92QgWtI4or:-OChwJFRBQR6K5lM4CN-:b4954pi) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L283)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Though it is nice and convenient to use the old promise chain syntax sometimes, the [code style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide) says to avoid using it where possible unless there is a compelling reason. Please change this to use `await` and `try/catch` or add a compelling reason in a code comment
</blockquote></details>

I've changed it, please have a look if this is better now
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 14 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdbeUD9p3g1DHju3fA:-OChwPTg6DSfunBYcI5S:bb7f2mf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This name is a bit confusing. This object is generally used as a sort of "default" object for `WebsiteViewerOptions` when there isn't another one, right? Maybe consider renaming `DEFAULT_WEBSITE_VIEWER_OPTIONS`?
</blockquote></details>

done
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 24 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdaFQpAVa0LI5yk-Sj:-OChwRxk14cg-dG0zbpL:bb7f2mf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L24)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We have traditionally made enumeration members `PascalCase` :) but I don't think we have explicit style rules about it, so do what you want with this information
</blockquote></details>

done
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 30 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdc3R7DIthnZd-pLBe:-OChxxjb-NoQ1G8AtPTe:bb7f2mf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Code style guide says to use verbs at the start of method names to make it clearer to understand what the variable is (I'd suggest maybe something like `createRange` or `createArrayOfIntegersBetween`). Additionally, I find this function hard to understand without reading the code because its name is not particularly descriptive. When that is the case, we usually try to make the method name more descriptive or put TSDocs on the method like this:

```typescript
/**
 * Some description
 *
 * @param start description
...
 */
```

Note VS Code will make this for you and include the parameters for you if you type `/**` and press enter above the method
</blockquote></details>

done
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 36 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCdd7tm0jyccQCi6euf:-OChxz5tE6nC9eiS1DHK:bb7f2mf) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L36)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This and the following function also need verbs at the start. Maybe just add `get` at the start?
</blockquote></details>

done
___
*[`src/website-viewer/src/websiteViewerOptions.ts` line 138 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_rELHCFWGKuzK8wXU:-OChyb6d1wZp9M3HrQyE:botk6w0) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/websiteViewerOptions.ts#L138)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If you make this `Map<keyof CommandHandlers | undefined, WebsiteViewerOptions>`, it might make it so you don't have  [...]

2024-11-27 14:33 UTC, Sebastian-ubs reviewed
Thank you TJ. I hope I applied all review comments.
The remaining issue I see is with imports, where I am not sure how to resolve them.
> Unable to resolve path to module 'papi-shared-types'.

> 'shared/services/scroll-group.service-model' import is restricted from being used by a pattern. Importing from this path is not allowed. Try importing from @papi/core. Imports from paths like 'shared', 'renderer', 'node', 'client' and 'main' are not allowed to prevent unnecessary import break.

> 'shared/services/web-view.service-model' import is restricted from being used by a pattern. Importing from this path is not allowed. Try importing from @papi/core. Imports from paths like 'shared', 'renderer', 'node', 'client' and 'main' are not allowed to prevent unnecessary import break.

> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-:-OCi0s2j3s_tqO6pkmV1:b-hvqeaq)* status: 36 of 42 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)



<!-- Sent from Reviewable.io -->

2024-12-02 16:09 UTC, tjcouch-sil requested changes
Thanks for your time and effort on the adjustments! It's very close :) just one more thing.

> Reviewed 2 of 6 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-:-OD77TEJ9Zaf2MiVL8gs:b-5aq1xo)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`src/website-viewer/src/main.ts` line 191 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_khY5EXpbcoS76esm:-OD75EMd3hdJJSdHbaRE:b-9oec4h) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L191)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

done  - although I am wondering about the real difference. comparing the two objects seems to work similarly good.
</blockquote></details>

Thanks for the update. Using an existing function makes it easier to change how that function works everywhere all at once in the future. :) For example, if we one day need to do some slightly different comparison with it or something, we can do that. Like if we one day take versification into account.
___
*[`src/website-viewer/src/main.ts` line 283 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OC_pNln7j92QgWtI4or:-OD76A82DR_9P0us7---:bf819r0) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/main.ts#L283)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

I've changed it, please have a look if this is better now
</blockquote></details>

Almost got it! Sorry, promises in TS are rather tricky. Doing a `forEach` on `commandPromises` will make it so the extension will finish activating before those promises resolve and add the unsubscribers to the registration inside the `forEach` because `forEach` doesn't work asynchronously; it all runs synchronously, so all the async function calls you're making inside it are not getting awaited anywhere. To properly wait on all the `commandPromises`, you can use `Promise.all` similarly to how you were doing it before. I think you should be able to do something like this:


```typescript
context.registrations.add(
  ...(await Promise.all(commandPromises)),
  await websiteViewerWebViewProviderPromise,
  ...
);
```

This awaits all the `commandPromises`, then destructures the returned array of unsubscribers to be added to `context.registrations` :)
___
*[`src/website-viewer/src/types/website-viewer.d.ts` line 77 at r2](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-OCd_T5vCoR9Z6ejhFwq:-OD73Lch71XTTj-yN6Cm:b8lpiow) ([raw file](https://github.com/paranext/platform-bible-sample-extensions/blob/10a7cf2bec1555b4555cddd0bfbfdb1b71c5b537/src/website-viewer/src/types/website-viewer.d.ts#L77)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

done, I was able to remove it, thanks.
</blockquote></details>

Thank you for your effort on it! :)


<!-- Sent from Reviewable.io -->

2024-12-02 18:01 UTC, tjcouch-sil approved these changes
Nice! Thanks again :) oh and thanks. And thank you! Oh and I just want to make sure I remembered to say thank you! Thank you!

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14#-:-OD7XAhg-dJhVvEF6_gz:b9b23sp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Sebastian-ubs)



<!-- Sent from Reviewable.io -->

2025-01-14 14:54 UTC, Sebastian-ubs commented
@tjcouch-sil the PR is ready for review / publish now

2025-01-14 14:55 UTC, Sebastian-ubs commented
oh, besides the comment saying I removed stuff - there is 1 thing I added: _allowPopups_ permission was added.

2025-01-27 17:56 UTC, tjcouch-sil approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/14)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Sebastian-ubs)



<!-- Sent from Reviewable.io -->

2025-01-28 07:50 UTC, Sebastian-ubs commented
Thank you TJ, since you completed
- https://github.com/paranext/paranext-core/issues/1369#event-16061922692
I guess I should include using this instead of the work around to open a new webview. Let me do it and get your review again...

2025-02-04 12:54 UTC, Sebastian-ubs commented
Since it is possible to merge I decided to make replacing the open method a new PR

2025-02-04 12:54 UTC, Sebastian-ubs commented
Since it is possible to merge I decided to make replacing the open method a new PR

2025-02-04 12:57 UTC, merged